steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fraudintel:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/fraudintel:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fraudintel:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fraudintel:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fraudintel'
      - '--image=gcr.io/$PROJECT_ID/fraudintel:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--timeout=300'
      - '--set-env-vars=APP_ENV=production'
images:
  - 'gcr.io/$PROJECT_ID/fraudintel:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fraudintel:latest'
timeout: '900s'
